### ISSUE TITLE
Extension will crash when there are more than two TargetFrameworks entries on csproj

### ISSUE THREAD

**Issue by yamachu** [yamachu/TargetFrameworksSwitcherForOmniSharp#4]
dump `innerPropertyGroup`

```
{
  TargetFrameworks: [
    'net8.0-maccatalyst',
    {
      '#text': '$(TargetFrameworks);net8.0-windows10.0.19041.0',
      '@_Condition': "$([MSBuild]::IsOSPlatform('windows'))"
    }
  ],
  OutputType: 'Exe',
  RootNamespace: 'CO2Widget',
  UseMaui: true,
  SingleProject: true,
  ImplicitUsings: 'enable',
  ApplicationTitle: 'CO2Widget',
  ApplicationId: 'com.companyname.co2widget',
  ApplicationDisplayVersion: 1,
  ApplicationVersion: 1,
  SupportedOSPlatformVersion: [
    {
      '#text': 11,
      '@_Condition': "$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'"
    },
    {
      '#text': 13.1,
      '@_Condition': "$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'"
    },
    {
      '#text': 21,
      '@_Condition': "$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'"
    },
    {
      '#text': '10.0.17763.0',
      '@_Condition': "$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'"
    },
    {
      '#text': 6.5,
      '@_Condition': "$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'"
    }
  ],
  TargetPlatformMinVersion: {
    '#text': '10.0.17763.0',
    '@_Condition': "$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'"
  },
  '@_Condition': "$(TargetFramework.Contains('-maccatalyst')) and '$(Configuration)' == 'Release'",
  CodesignEntitlements: 'Platforms/MacCatalyst/Entitlements.Release.plist',
  UseHardenedRuntime: true
}
```

```
TypeError: (innerPropertyGroup[Constants_1.CSPROJ_PROPERTY_TargetFrameworks] ?? "").split is not a function
    at parseCsproj (/Users/yamachu/Projects/github.com/yamachu/NodeCsprojModifier/dist/src/Domains.js:19:103)
    at async Promise.all (index 0)
    at async Object.listing (/Users/yamachu/Projects/github.com/yamachu/NodeCsprojModifier/dist/src/Usecases.js:44:47)
```

we must detect `TargetFrameworks` is array or string.

**Comment by yamachu** [comment]
Fixed: https://github.com/yamachu/TargetFrameworksSwitcherForOmniSharp/pull/5
